import { IAttachment, IEvent, IIdentity, ISuggestedActions } from "botbuilder";
import { IBag, IVoxaEvent } from "../../VoxaEvent";
import { IVoxaReply } from "../../VoxaReply";
import { BotFrameworkEvent } from "./BotFrameworkEvent";
import { IAuthorizationResponse } from "./BotFrameworkInterfaces";
export declare class BotFrameworkReply implements IVoxaReply {
    private event;
    readonly hasMessages: boolean;
    readonly hasDirectives: boolean;
    readonly hasTerminated: boolean;
    readonly speech: string;
    channelId: string;
    conversation: IIdentity;
    from: IIdentity;
    id?: string;
    inputHint: string;
    locale: string;
    recipient: IIdentity;
    replyToId?: string;
    speak: string;
    text: string;
    textFormat: string;
    timestamp: string;
    type: string;
    attachments?: IAttachment[];
    suggestedActions?: ISuggestedActions;
    attachmentLayout?: string;
    constructor(event: BotFrameworkEvent);
    toJSON(): Partial<this>;
    clear(): void;
    terminate(): void;
    addStatement(statement: string, isPlain?: boolean): void;
    hasDirective(type: string | RegExp): boolean;
    addReprompt(reprompt: string): void;
    send(): Promise<void>;
    botApiRequest(method: string, uri: string, reply: BotFrameworkReply, event: BotFrameworkEvent, attempts?: number): Promise<any>;
    getReplyUri(event: IEvent): string;
    getAuthorization(applicationId?: string, applicationPassword?: string): Promise<IAuthorizationResponse>;
    saveSession(attributes: IBag, event: IVoxaEvent): Promise<void>;
}
